# Generated by Django 6.0.2 on 2026-02-17 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_categoria_tarea_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarea',
            options={'ordering': ['-fecha_creacion'], 'verbose_name_plural': 'Mis Tareas'},
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.CharField(choices=[('B', 'Baja'), ('M', 'Media'), ('A', 'Alta')], default='M', max_length=1),
        ),
    ]
